export const POPULATE_APPLICATIONS = 'POPULATE_APPLICATIONS';
export const UPDATE_APPLICATION_LOADER = 'UPDATE_CUSTOMERS_LOADER';
export const UPDATE_SELECTED_APPLICATION = 'UPDATE_SELECTED_CUSTOMER';
export const UPDATE_APPLICATION_PAGINATION = 'UPDATE_CUSTOMER_PAGINATION';
export const UPDATE_APPLICATION_PAGINATION_LINKS = 'UPDATE_APPLICATIONPAGINATION_LINKS';
